# 성분으로 구성한 아이스크림 총 주문량
# https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I, FIRST_HALF F
WHERE I.FLAVOR=F.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;