SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

-- Join으로도 가능 -- 
-- SELECT 
-- 	A.FOOD_TYPE,
-- 	A.REST_ID, 
-- 	A.REST_NAME, 
-- 	A.FAVORITES
-- FROM REST_INFO AS A
-- RIGHT JOIN 
-- (SELECT 
-- 	FOOD_TYPE, 
-- 	max(FAVORITES) as max_favorites 
-- 	FROM REST_INFO 
-- 	group by FOOD_TYPE) AS B
-- on A.FOOD_TYPE=B.FOOD_TYPE and A.FAVORITES=B.max_favorites
-- order by FOOD_TYPE DESC