SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) as TOTAL_SALES
FROM BOOK B JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID 

JOIN BOOK_SALES S
ON S.BOOK_ID = B.BOOK_ID

WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m')='2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC